### ISSUE TITLE
it says the zip is invalid

### ISSUE THREAD

**Issue by EnderBoi201** [GeopJr/exorcism#1]
![fhfhfhfdhssbiniofdb](https://user-images.githubusercontent.com/100241364/193187286-bed02e92-eed2-4b73-a09f-bd1e24efedaa.png)

**Comment by EnderBoi201** [comment]
nvm i can open it with winrar

**Comment by GeopJr** [comment]
Glad you got it fixed!

I don't have a Windows machine so I can't really help with Windows issues.
