### ISSUE TITLE
add to scoop bucket

### ISSUE THREAD

**Issue by vvirtues** [GeopJr/exorcism#3]
should be very simple. i believe it belongs in the `extras`, but don't blame me if i'm wrong

**Comment by GeopJr** [comment]
Thanks for raising this issue!

While it does sound good for it to be on Windows repos, it probably shouldn't.

I've never "officially" tested it on Windows and the (only) CI build is mostly guesswork. I know it works on Windows... at least it did 2 years ago.

Additionally, I am unsure of its *stability*. It was written 2 years ago in an attempt to try out nodegui - which was extremely experimental then.

For those reasons I ask anyone planning on packaging it, to not do it.
